version: '3.4'

services:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "dewasmith2350"
      ACCEPT_EULA: "Y"